name: Deploy Dockerhub

on:
  push:
    branches:
      - in-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Restore Maven Package
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t chichia/moto:latest .

      - name: Free up port 8082 (if in use)
        run: ssh -o StrictHostKeyChecking=no -i aws_key.pem ubuntu@${{ secrets.AWS_IP_ADDRESS }} "sudo fuser -k 8082/tcp"

      - name: Pull and run Docker container
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PEM }}
          INSTANCE_IP: ${{ secrets.AWS_IP_ADDRESS }}
        run: |
          echo "$PRIVATE_KEY" > aws_key.pem
          chmod 600 aws_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H $INSTANCE_IP >> ~/.ssh/known_hosts
          ssh -i aws_key.pem ubuntu@$INSTANCE_IP << 'EOF'
            # Stop and remove any existing container with the same name
            if [ "$(docker ps -aq -f name=moto-class-container)" ]; then
              docker stop moto-class-container
              docker rm moto-class-container
            fi

            # Pull the latest Docker image
            docker pull chichia/moto:latest

            # Run the new container with the correct port mapping (8083 on the host)
            sudo docker run -d --name moto-class-container -p 8083:8081 chichia/moto:latest
          EOF
