#name: Deploy to AWS EC2
#
#on:
#  push:
#    branches:
#      - in-dev
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Restore Maven Package
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('/*.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build Docker image
#        run: docker build -t chichia/moto:latest .
#
#      - name: Push Docker image to Docker Hub
#        run: docker push chichia/moto:latest
#
#      - name: Create PEM file
#        run: |
#          echo "${{ secrets.AWS_PEM }}" > aws_key.pem
#          chmod 400 aws_key.pem
#
#      - name: Deploy to AWS EC2
#        run: |
#          ssh -o StrictHostKeyChecking=no -i aws_key.pem ubuntu@${{ secrets.AWS_IP_ADDRESS }} << 'EOF'
#             # Add ubuntu user to docker group
#             sudo usermod -aG docker ubuntu
#
#             # Restart docker service
#             sudo systemctl restart docker
#
#             # Refresh user session (forces Docker group permissions)
#             exit
#          EOF
#
#      - name: Pull and run Docker container
#        run: |
#          ssh -o StrictHostKeyChecking=no -i aws_key.pem ubuntu@${{ secrets.AWS_IP_ADDRESS }} << 'EOF'
#             # Stop and remove any existing container with the same name
#             if [ "$(docker ps -aq -f name=moto-class-container)" ]; then
#               docker stop moto-class-container
#               docker rm moto-class-container
#             fi
#
#             # Pull the latest Docker image
#             docker pull chichia/moto:latest
#
#             # Run the new container with the .env file
#             sudo docker run -d --env-file=.env --name moto-class-container -p 8080:8082 chichia/moto:latest
#          EOF
#

name: Deploy Dockerhub

on:
  push:
    branches:
      - in-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Restore Maven Package
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t chichia/moto:latest .

      - name: Push Docker image to Docker Hub
        run: docker push chichia/moto:latest

      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PEM }}
          INSTANCE_IP: ${{ secrets.AWS_IP_ADDRESS }}
        run: |
          echo "$PRIVATE_KEY" > aws_key.pem
                 chmod 600 aws_key.pem
                 mkdir -p ~/.ssh
                 ssh-keyscan -H $INSTANCE_IP >> ~/.ssh/known_hosts
                 ssh -i aws_key.pem ubuntu@$INSTANCE_IP << 'EOF'
                   sudo docker pull chichia/moto:latest
                   sudo docker run -d -p 8081:8081 chichia/moto:latest
          EOF

      - name: Pull and run Docker container
        run: |
          ssh -o StrictHostKeyChecking=no -i aws_key.pem ubuntu@${{ secrets.AWS_IP_ADDRESS }} << 'EOF'
             # Stop and remove any existing container with the same name
             if [ "$(docker ps -aq -f name=moto-class-container)" ]; then
               docker stop moto-class-container
               docker rm moto-class-container
             fi
          
             # Pull the latest Docker image
             docker pull chichia/moto:latest
          
             # Run the new container with the .env file
             sudo docker run -d --env-file=.env --name moto-class-container -p 8080:8082 chichia/moto:latest
          EOF

